TARGET_COMPANIES = [
    {"name": "汇丰银行（中国）", "group": "汇丰集团", "url": "https://www.hsbc.com.cn/careers/", "excluded": False},
    {"name": "汇丰科技", "group": "汇丰集团", "url": "https://www.hsbc.com/careers/", "excluded": False},
    {"name": "汇丰保险", "group": "汇丰集团", "url": "https://www.hsbcinsurance.com/careers/", "excluded": False},
    {"name": "汇丰前海证券", "group": "汇丰集团", "url": "https://www.hsbc.com.cn/careers/", "excluded": False},
    {"name": "恒生银行", "group": "汇丰集团", "url": "https://www.hangseng.com/careers/", "excluded": False},
    {"name": "招商局集团", "group": "招商集团", "url": "https://www.cmhk.com/careers/", "excluded": False},
    {"name": "招商银行", "group": "招商集团", "url": "https://career.cmbchina.com/", "excluded": False},
    {"name": "招商证券", "group": "招商集团", "url": "https://www.cmschina.com/careers/", "excluded": False},
    {"name": "招商蛇口", "group": "招商集团", "url": "https://www.cmsk.com/careers/", "excluded": False},
    {"name": "招商局港口", "group": "招商集团", "url": "https://www.cmport.com.hk/careers/", "excluded": False},
    {"name": "招商局工业集团", "group": "招商集团", "url": "https://www.cmindustry.com/careers/", "excluded": False},
    {"name": "招商局能源运输", "group": "招商集团", "url": "https://www.cmenergyshipping.com/careers/", "excluded": False},
    {"name": "招商局资本", "group": "招商集团", "url": "https://www.cmcapital.com/careers/", "excluded": False},
    {"name": "招商局公路", "group": "招商集团", "url": "https://www.cmhighway.com/careers/", "excluded": False},
    {"name": "华为", "group": "华为", "url": "https://career.huawei.com/", "excluded": False},
    {"name": "大疆创新", "group": "大疆", "url": "https://we.dji.com/zh-CN/", "excluded": False},
    {"name": "沃尔玛（中国）", "group": "沃尔玛集团", "url": "https://www.walmartcareers.com/", "excluded": False},
    {"name": "山姆会员商店", "group": "沃尔玛集团", "url": "https://www.walmartcareers.com/", "excluded": False},
    {"name": "谷歌中国", "group": "谷歌", "url": "https://careers.google.com/", "excluded": False},
    {"name": "摩根大通（中国）", "group": "摩根大通", "url": "https://careers.jpmorgan.com/", "excluded": False},
    {"name": "字节跳动", "group": "字节跳动", "url": "https://jobs.bytedance.com/", "excluded": False},
    {"name": "腾讯", "group": "腾讯", "url": "https://careers.tencent.com/", "excluded": False},
    {"name": "阿里巴巴", "group": "阿里巴巴", "url": "https://talent.alibaba.com/", "excluded": False},
    {"name": "蚂蚁集团", "group": "阿里巴巴", "url": "https://talent.antgroup.com/", "excluded": False},
    {"name": "美团", "group": "美团", "url": "https://zhaopin.meituan.com/", "excluded": False},
    {"name": "京东", "group": "京东", "url": "https://zhaopin.jd.com/", "excluded": False},
    {"name": "百度", "group": "百度", "url": "https://talent.baidu.com/", "excluded": False},
    {"name": "微软（中国）", "group": "微软", "url": "https://careers.microsoft.com/", "excluded": False},
    {"name": "亚马逊（中国）", "group": "亚马逊", "url": "https://www.amazon.jobs/", "excluded": False},
    {"name": "埃森哲（中国）", "group": "埃森哲", "url": "https://www.accenture.com/cn-zh/careers", "excluded": False},
    {"name": "IBM（中国）", "group": "IBM", "url": "https://www.ibm.com/careers/cn/", "excluded": False},
    {"name": "SAP（中国）", "group": "SAP", "url": "https://www.sap.com/careers.html", "excluded": False},
    {"name": "中兴通讯", "group": "中兴", "url": "https://www.zte.com.cn/china/careers/", "excluded": False},
    {"name": "荣耀", "group": "荣耀", "url": "https://www.hihonor.com/careers/", "excluded": False},
    {"name": "华润集团", "group": "华润集团", "url": "https://www.crc.com.cn/careers/", "excluded": False},
    {"name": "中粮集团", "group": "中粮集团", "url": "https://www.cofco.com/careers/", "excluded": False},
    {"name": "中国移动", "group": "中国移动", "url": "https://www.10086.cn/careers/", "excluded": False},
    {"name": "微众银行", "group": "腾讯系", "url": "https://www.webank.com/careers/", "excluded": False},
    {"name": "众安保险", "group": "众安", "url": "https://www.zhongan.com/careers/", "excluded": False},
    {"name": "渣打银行（中国）", "group": "渣打集团", "url": "https://www.sc.com/cn/careers/", "excluded": False},
    {"name": "花旗银行（中国）", "group": "花旗集团", "url": "https://www.citi.com.cn/careers/", "excluded": False},
    {"name": "星展银行（中国）", "group": "星展集团", "url": "https://www.dbs.com.cn/careers/", "excluded": False},
]
EXCLUDED_COMPANIES = ["平安","平安银行","平安寿险","平安产险","平安养老险","平安健康险","平安证券","平安基金","平安信托","平安租赁","平安科技","平安普惠","平安医保科技","平安好医生","平安壹账通","平安城科","平安不动产","平安金融科技","平安健康检测中心","平安壹钱包"]
SEARCH_KEYWORDS = ["财务总监","CFO","财务副总裁","数字化转型","数字化战略","首席数字官","CDO","战略总监","战略规划","战略管理","科技财务","财务共享","业财一体","科技成本管理","研发管理","管理咨询","咨询总监","咨询合伙人"]
PREFERRED_LOCATIONS = ["深圳","香港","广州"]
SALARY_MIN = 5
SALARY_MAX = 8
